name: local
variables:
  - name: baseUrl
    value: http://localhost:3000
  - name: loginEmail
    value: test.bruno@test.fr
  - secret: true
    name: loginPassword
  - secret: true
    name: resetToken
  - secret: true
    name: newPassword
  - secret: true
    name: accessToken
  - name: categorieId
    value: 06c64f76-ea2b-4204-87c4-8760412f803c
  - name: equipeId
    value: 2791e559-a098-4744-81a7-050059b513cd
  - name: equipeNom
    value: Equipe Test Bruno
  - name: roleId
    value: ""
  - name: roleLibelle
    value: Role Test Bruno
